### ISSUE TITLE
I can't build your fork of libgit2

### ISSUE THREAD

**Issue by wiiznokes** [jakubslaby09/libgit2-android#1]
Hello, I'm working on an Android app at the moment that requires git. So I came across your fork and it's a bit of a blessing for me.

I managed to do all the steps, except build `libgit2`, I came across a slightly strange error:

```sh
$ cmake --build .
[  0%] Built target http-parser
[  3%] Built target pcre
[  5%] Built target xdiff
[  5%] Building C object deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o
In file included from /home/lenaic/Documents/gitnote/app/src/main/cpp/libgit2/deps/ntlmclient/ntlm.c:19:
In file included from /home/lenaic/Documents/gitnote/app/src/main/cpp/libgit2/deps/ntlmclient/ntlm.h:14:
In file included from /home/lenaic/Documents/gitnote/app/src/main/cpp/libgit2/deps/ntlmclient/crypt.h:16:
/home/lenaic/Documents/gitnote/app/src/main/cpp/libgit2/deps/ntlmclient/crypt_openssl.h:13:11: fatal error: 'openssl/des.h' file not found
# include <openssl/des.h>
          ^~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [deps/ntlmclient/CMakeFiles/ntlmclient.dir/build.make:76 : deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:370 : deps/ntlmclient/CMakeFiles/ntlmclient.dir/all] Erreur 2
gmake: *** [Makefile:146 : all] Erreur 2
```

but obviously, `des.h` exist:
```shell
ls ./../openssl/include/openssl/des*
./../openssl/include/openssl/des.h
```

And it seems included in the build system: `list(APPEND CMAKE_FIND_ROOT_PATH openssl/include)`

thank you in advance for your help

**Comment by wiiznokes** [comment]
Hi have now the same issue you had: https://stackoverflow.com/questions/77162491/how-do-i-compile-libgit2-for-android

**Comment by jakubslaby09** [comment]
Hi, thanks for creating an issue, I will extend the readme based on this.

In [my f-droid metadata file](https://gitlab.com/fdroid/fdroiddata/-/commit/cfdfa250c71440dec4defc918e927ad52b42d7f5#04415b3b61f6e70c595c8763d584d671257614b5), I have used this command to get that inline syntax mentioned in the stackoverflow question to work:
```shell
find .. -name 'CMakeLists.txt' -exec sed -i 's|C_STANDARD 90|C_STANDARD 99|' {} \;
``` 

Then, you need to ignore an error not present in C90. Adding this to the toolchain file should be enough:
```cmake
add_compile_options(-Wno-implicit-function-declaration)
```

I think I got it from [this issue](https://github.com/libgit2/libgit2/issues/6574#issuecomment-1642974971).

**Comment by wiiznokes** [comment]
Thanks for sharing all of this, i was finally able to build `libgit2`. 

Unfortunately, I have a problem when calling the `git_libgit2_init` function. It gives me this error: `error, 16 could not load ssl libraries`.
However, I have setup my libs well I think
![Capture d’écran du 2023-11-04 01-29-51](https://github.com/jakubslaby09/libgit2-android/assets/78230769/212ee8f5-ba26-4f4a-bd87-c4275618d0d8)
